// JavaScript source code

function random_name()
{
    var num = Math.floor(Math.random()*101);
    switch (num)
    {
        case 0: return "Alex";
        case 1: return "Noel";
        case 2: return "Jared";
        case 3: return "Anthony";
        case 4: return "Ted";
        case 5: return "Magda";
        case 6: return "Richert";
        case 7: return "Amanda";
        case 8: return "Jimmy";
        case 9: return "Jimbo";
        case 10: return "Fake Name";
        case 11: return "Jim Morrison";
        case 12: return "Cat";
        case 13: return "Dog";
        case 14: return "Mongoose";
        case 15: return "Not a Bear";
        case 16: return "Obama";
        case 17: return "Trump";
        case 18: return "Hilary";
        case 19: return "Thomas";
        case 20: return "Rebecca";
        case 21: return "Toast";
        case 22: return "The Monkey";
        case 23: return "The Dude";
        case 24: return "Abe";
        case 25: return "Richard Nixon";
        case 26: return "Apple";
        case 27: return "Pear";
        case 28: return "Bananananananaaanan";
        case 29: return "Earth";
        case 30: return "Sun";
        case 31: return "Mars";
        case 32: return "Pluto is a Planet";
        case 33: return "ERROR";
        case 34: return "The Man";
        case 35: return "The Women";
        case 36: return "Pete";
        case 37: return "Chan";
        case 38: return "La-a";
        case 39: return "Rosina";
        case 40: return "Joe";
        case 41: return "Carlyn";
        case 42: return "Caaaaarl";
        case 43: return "The Other Lama";
        case 44: return "Iva";
        case 45: return "Brad";
        case 46: return "Beattlejuice";
        case 47: return "COGS Lab";
        case 48: return "INVALID NAME";
        case 49: return "Faced";
        case 50: return "Ned Balldera";
        case 51: return "I. P. Freely";
        case 52: return "Heywood Yapinchme";
        case 53: return "Al Choholic";
        case 54: return "Oliver Klozoff";
        case 55: return "Chris P. Bacon";
        case 56: return "Sparky";
        case 57: return "Alien";
        case 58: return "Aliens";
        case 59: return "Alien 3";
        case 60: return "Alien 4: Reserection";
        case 61: return "A New Hope";
        case 62: return "The Force Awakens";
        case 63: return "TR8R";
        case 64: return "Ash Ketchup";
        case 65: return "Ash Gotta Catch Em' All";
        case 66: return "The Ear Mike Tyson Ate";
        case 67: return "Mom";
        case 68: return "Dad";
        case 69: return "Your Laptop";
        case 70: return "gameState=GAMEOVER";
        case 71: return "The Best";
        case 72: return "The Worst";
        case 73: return "Gluttony";
        case 74: return "Pride";
        case 75: return "Envy";
        case 76: return "Sloth";
        case 77: return "Wrath";
        case 78: return "Greed";
        case 79: return "Lust";
        case 80: return "Door";
        case 81: return "Window";
        case 82: return "Thrall";
        case 83: return "Arthas";
        case 84: return "Illidan";
        case 85: return "Sylvannas";
        case 86: return "Jaina";
        case 87: return "Garrosh";
        case 88: return "Medivh";
        case 89: return "Kael'Thas";
        case 90: return "Anduin";
        case 91: return "Varian";
        case 92: return "A Guy Named Sue";
        case 93: return "Lou";
        case 94: return "This name is too lo";
        case 95: return "NOT_AN_AI";
        case 96: return "Lasganhia";
        case 97: return "The 99%";
        case 98: return "THE BEST NAME";
        case 99: return "Winner";
        case 100: return "Loser";
        default: return "Player" + num;
    }
}